# Generated by Django 4.0 on 2022-09-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0007_appliedjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newstext', models.TextField()),
                ('newsdate', models.CharField(max_length=30)),
            ],
        ),
    ]
